Readme
westonio/next-steps-front-end pull request #35
Opened 2023-09-13 00:15 UTC by garussell

### Description of changes

### Screenshots (if applicable) of relevant views

### Test Suite
- [x] Are all tests within the test suite passing?

### Specific Feedback Request(s)

#### Add GIF (NOT Optional)

<img src="https://media0.giphy.com/media/l0K4kWJir91VEoa1W/giphy.gif"/>

2023-09-13 01:02 UTC, JorjaF requested changes
Hey there are a couple of things that we wanted to tweek a bit, but this looks really great. thank you for setting that up/

2023-09-14 17:38 UTC, garussell reviewed
Requested changes complete.

2023-09-14 17:38 UTC, garussell commented on README.md
Done

2023-09-16 16:12 UTC, kcockett approved these changes
Changes look good to me

2023-09-16 16:19 UTC, kcockett approved these changes
Changes were completed.  This looks good.

2023-09-17 00:15 UTC, merged